const suffix = {
  'html' : 'text/html',  
  'css'  : 'text/css',  
  'js'   : 'text/javascript',  
  'json' : 'application/json',  
  'ico'  : 'image/x-icon',  
  'gif'  : 'image/gif',  
  'jpeg' : 'image/jpeg',  
  'jpg'  : 'image/jpeg',  
  'png'  : 'image/png',  
  'pdf'  : 'application/pdf',  
  'svg'  : 'image/svg+xml',  
  'swf'  : 'application/x-shockwave-flash',  
  'tiff' : 'image/tiff',  
  'txt'  : 'text/plain',  
  'wav'  : 'audio/x-wav',  
  'wma'  : 'audio/x-ms-wma',  
  'wmv'  : 'video/x-ms-wmv',  
  'xml'  : 'text/xml'  
}